---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# file-sed-regex-action
name: "String Substitution in File (using sed)"
description: "Performs string substitutions using the command-line tool, sed"

inputs:
  # Mandatory
  FLAGS:
    description: "Flags to use with SED command"
    required: false
    default: "-i"
  REGEX:
    description: "Search/replace expression"
    required: true
  PATH:
    description: "Path to local file to modify"
    required: true
  # Optional
  NO_FAIL:
    description: "Override errors if file not found or no value returned"
    required: false
    default: "false"

outputs:
  EXIT_STATUS:
    description: "Exit status of sed command"
    value: ${{ steps.sed.outputs.exit_status }}

runs:
  using: "composite"
  steps:
    - name: "Perform string substitution in: ${{ inputs.PATH }}"
      id: sed
      shell: bash
      run: |
        # Perform string substitution in: ${{ inputs.PATH }}

        SED_CMD=$(which sed)
        if [ ! -x "$SED_CMD" ]; then
          echo "Error: sed command not in PATH ❌"
          exit 1
        fi

        FILE_PATH="${{ inputs.PATH }}"
        if [ -z "$FILE_PATH" ]; then
          echo "Error: input variable/path cannot be empty ❌"
          exit 1
        elif [ ! -f "$FILE_PATH" ]; then
          echo -n "Error: file not found "
          if [ "${{ inputs.NO_FAIL }}" = "true" ]; then
            echo "⚠️"
            echo "Path: $FILE_PATH"
            exit 0
          else
            echo "❌"
            echo "Path: $FILE_PATH"
            exit 1
          fi
        fi

        set -o noglob
        "$SED_CMD" '${{ inputs.FLAGS }}' '${{ inputs.REGEX }}' "$FILE_PATH"
        EXIT_STATUS="$?"
        echo "exit_status=$EXIT_STATUS" >> "$GITHUB_OUTPUT"
        if [ "$EXIT_STATUS" != "0" ]; then
          echo -n "Error: sed command failed with exit status $EXIT_STATUS "
          if [ "${{ inputs.NO_FAIL }}" = "true" ]; then
            echo "⚠️"
            exit 0
          else
            echo "❌"
            $EXIT_STATUS
          fi
        else
          echo "exit_status=0" >> "$GITHUB_OUTPUT"
          echo "Successful ✅ "
        fi
